export const USER_LOGGED_IN_STATUS = 'USER_LOGGED_IN_STATUS';
export const IS_USER_FIRST_TIME_BOARDING = 'IS_USER_FIRST_TIME_BOARDING';
export const FCM_TOKEN = 'FCM_TOKEN';
export const APP_LOADING_SPINNER = 'APP_LOADING_SPINNER';
export const INTERNET_STATUS = 'INTERNET_STATUS';
export const PAYMENT_CARD_LIST_DATA = 'PAYMENT_CARD_DATA';

export const CLASS_SUCCESS = 'CLASS_SUCCESS';
export const CLASS_FAILURE = 'CLASS_FAILURE';
export const CLASS_LOADING = 'CLASS_LOADING';

export const SUBJECT_SUCCESS = 'SUBJECT_SUCCESS';
export const SUBJECT_FAILURE = 'SUBJECT_FAILURE';
export const SUBJECT_LOADING = 'SUBJECT_LOADING';

